### ISSUE TITLE
Egg lay multiply doesnt affect new chicken variants

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [OmerBenGera/WildStacker#1087]
### Minecraft's Version

This server is running Paper version 1.21.8-60-main@29c8822 (2025-09-06T21:49:13Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.8-304b8ee (MC: 1.21.8)

### Plugin's Version

2025.1-b164

### Describe the bug

White chickens are multiplaying eggs accoring to their stack size, but Blue and Warm chickens doesnt and lay only one egg.

### To Reproduce

Spawn white and warm chicken with stacks of 10.
/tick rate 2000
There would be 10 white eggs and only one warm laid

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by Kryniowesegryderiusz** [comment]
Unfortunately that didnt fix the issue (also on /version the build name is b164, even if the file name is 165)

**Comment by OmerBenGera** [comment]
> Unfortunately that didnt fix the issue (also on /version the build name is b164, even if the file name is 165)

This means you're on 164 and not 165.
Make sure there are not multiple jars of the plugin in your plugins folder

**Comment by Kryniowesegryderiusz** [comment]
Yes, my bad, everything works fine, but I have no idea, where have I uploaded b165 file before, there was only b164. I needed some sleep 😆
